### ISSUE TITLE
Missing instructions for running tests

### ISSUE THREAD

**Issue by khinsen** [vsoch/gridtest#29]
The installation instructions should indicate how to run the test suite, and in particular mention the dependency of the tests on the [pokemon](https://pypi.org/project/pokemon/) package.

**Comment by vsoch** [comment]
Thank you for pointing this out! I've added the missing documentation to the install page:
https://vsoch.github.io/gridtest/install/

![image](https://user-images.githubusercontent.com/814322/84029494-b6a50500-a94f-11ea-8148-d06d1c4dcf08.png)
