### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by cbrueffer** [vsoch/gridtest#31]
### Description

Tthe `Community guidelines` section of the JOSS review mentions instructions for contributors to the software. Adding a contributing file as per https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors would cover this.

**Comment by vsoch** [comment]
I'd be happy to! Also note that we already have a guide in the documentation https://vsoch.github.io/gridtest/contributing/index.html. Would you prefer a standard CONTRIBUTING.md added, or perhaps a link to that page in the README?

**Comment by cbrueffer** [comment]
To me, specific sections in the README are usually best, since they are very visible. I think the information in the guide is fine, so no CONTRIBUTING file is needed.

**Comment by vsoch** [comment]
All set! https://github.com/vsoch/gridtest/commit/002de28e6529d99082baab9864027974c3c361a5 I did the following:

 - added a CONTRIBUTING.md guide which has more of a "PR checklist" along with code of conduct
 - linked to the "how to contribute to docs and code" in the README, along with the link to the checklist.

I figure there are two use cases to wanting to contribute - either wanting the checklist (CONTRIBUTING.md) or the pretty, rendered guide, so we can link to both.

**Comment by cbrueffer** [comment]
Looks good, thanks! I think moving the pointer to the documentation from the end of the overview to its own Documentation section would be good to make it more obvious. It gets a bit lost in its current location.

**Comment by vsoch** [comment]
Sure thing. Also note that the link is right at the top (I usually look for it there)
![image](https://user-images.githubusercontent.com/814322/85050669-a9f48e00-b153-11ea-9aa1-78f07791fab2.png)

**Comment by vsoch** [comment]
Added to the top!
![image](https://user-images.githubusercontent.com/814322/85050827-ed4efc80-b153-11ea-9525-d80843f28e9f.png)

**Comment by cbrueffer** [comment]
Didn't even notice that! It's probably a very personal thing on what we focus on first when skimming a repo.

**Comment by cbrueffer** [comment]
Off-topic for this PR but I noticed that gridtest isn't tested using gridtest from the CI, is there a reason for that?

**Comment by cbrueffer** [comment]
Addressed in https://github.com/vsoch/gridtest/commit/002de28e6529d99082baab9864027974c3c361a5, https://github.com/vsoch/gridtest/commit/7d97d88fdefe6554158b403db22ef1dc31b0ab79, and https://github.com/vsoch/gridtest/commit/38dad3a2f5eeac70178158c258b5e874c83b8621
