### ISSUE TITLE
Paper: discussion of state of the art

### ISSUE THREAD

**Issue by cbrueffer** [vsoch/gridtest#34]
### Description

Reading the paper with the JOSS review checklist in mind, one thing I find missing is a discussion of the current state of the art, both in terms GridTest as a testing tool, and as a grid generation tool.

From an online search, there seem to be several software tools in the general "grid generation" space and even some theory behind it. Examples would be https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.ParameterGrid.html and (non-Python) https://rdrr.io/cran/dials/man/grid_regular.html.

**Comment by vsoch** [comment]
I can definitely add a few lines to compare these! Give me a few minutes.

**Comment by cbrueffer** [comment]
The two mentioned above are just examples from a quick search; what would be nice is a bit more thorough survey of what's out there, how GridTest compares to them, and what it adds. I think this goes a bit in the direction of what @khinsen referred to to with "statement of need".

**Comment by vsoch** [comment]
All set! https://github.com/vsoch/gridtest/pull/35
