### ISSUE TITLE
Errors/suggestions needed for JOSS publication of paper.

### ISSUE THREAD

**Issue by usethedata** [vsoch/gridtest#40]
### Description

This issue lists corrections and suggestions for items related to the publication of the Gridtest paper in JOSS.

### Corrections requested

- [x] In the paper, the link for "how does it work" is 404 (https://vsoch.github.io/gridtest/getting-started/index.html%23how-does-it-work)
- [x] In the paper, the link for "loading grids via a GridRunner is 404 (https://vsoch.github.io/gridtest/getting-started/grids/index.html%23loading-via-a-gridrunner)

### Additional steps needed

- [x] Once the above corrections have been made and committed, make a tagged release.
- [x] Archive the tagged release, e.g. with [Figshare](https://figshare.com/) or [Zenodo](https://zenodo.org/)
- [x] Post the version tag and the DOI for the archived version on the [JOSS review issue](https://github.com/openjournals/joss-reviews/issues/2284)

Once those items are done, I can move to my next steps.

**Comment by vsoch** [comment]
working on these now!

**Comment by vsoch** [comment]
- [x] Links are [fixed](https://github.com/vsoch/gridtest/pull/41) (I checked the branch with the Joss Paper Preview / Whedon tool)
 - [x] A [new release is made](https://github.com/vsoch/gridtest/releases/tag/0.0.15) although the [doi seems to not be ready yet](https://doi.org/10.5281/zenodo.3930366). I needed to update my author name so I'll wait for that page to render to do that. I'll still post both on the JoSS issue, and please close here when you are happy with the changes!
